services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    networks:
      - spark-cluster-network
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      INIT_DAEMON_STEP: setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    networks:
      - spark-cluster-network
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G

  spark-worker-2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-2
    networks:
      - spark-cluster-network
    ports:
      - 8082:8081
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G

  spark-client:
    image: bde2020/spark-submit:3.0.1-hadoop3.2
    container_name: spark-client
    networks:
      - spark-cluster-network
    ports:
      - 4040:4040
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
    volumes:
      - ./app:/spark/bin/app
    stdin_open: true
    tty: true
    command: bash
  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - spark-cluster-network
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - spark-cluster-network
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true  # Enable auto-creation of topics
    depends_on:
      - zookeeper

networks:
  spark-cluster-network:
    name: spark-cluster-network
    driver: bridge