services:
  spark-master:
    image: wensespl/spark-master:1.0
    container_name: spark-master
    ports:
      - "8080:8080"
    networks:
      - spark-net
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==master
  
  spark-worker-1:
    image: wensespl/spark-worker:1.0
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - CORES=3
      - MEMORY=15G
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==worker
    networks:
      - spark-net
  
  spark-worker-2:
    image: wensespl/spark-worker:1.0
    container_name: spark-worker-2
    ports:
      - "8082:8081"
    environment:
      - CORES=3
      - MEMORY=15G
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==worker
    networks:
      - spark-net

  spark-client:
    image: wensespl/spark-submit:1.0
    container_name: spark-client
    networks:
      - spark-net
    ports:
      - "4040:4040"
    stdin_open: true
    tty: true
    command: bash

networks:
  spark-net:
    driver: bridge