version: '3.8'

services:
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    networks:
      - spark-cluster-network
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      INIT_DAEMON_STEP: setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-1
    networks:
      - spark-cluster-network
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G

  spark-worker-2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker-2
    networks:
      - spark-cluster-network
    ports:
      - 8082:8081
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G

  spark-client:
    image: bde2020/spark-submit:3.0.1-hadoop3.2
    container_name: spark-client
    networks:
      - spark-cluster-network
    ports:
      - 4040:4040
    depends_on:
      - spark-master
      - kafka
      - postgres
    environment:
      SPARK_MASTER: spark://spark-master:7077
    volumes:
      - ./app:/spark/bin/app
    stdin_open: true
    tty: true
    command: bash
  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - spark-cluster-network
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - spark-cluster-network
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true  # Enable auto-creation of topics
    depends_on:
      - zookeeper

  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - spark-cluster-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      - spark-cluster-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  superset:
    image: apache/superset
    container_name: superset
    networks:
      - spark-cluster-network
    environment:
      SUPERSET_SECRET_KEY: 'thisISaSECRET_1234'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      SUPERSET_DB__URI: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./superset_home:/app/superset_home
    ports:
      - 8088:8088
    command:
      - sh
      - -c
      - |
        superset db upgrade &&
        export FLASK_APP=superset && \
        flask fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin && \
        superset init &&
        superset run -p 8088 -h 0.0.0.0 --with-threads --reload --debugger

networks:
  spark-cluster-network:
    name: spark-cluster-network
    driver: bridge
